version: 0.2
phases:
    build:
     commands:
      - sudo yarn install
      - sudo yarn build
      - aws cloudfront create-invalidation --distribution-id="E2GTYUKJ7GEAQ1" --paths "/*"     
    post_build:
     commands:
      - aws cloudfront create-invalidation --distribution-id="E2GTYUKJ7GEAQ1" --paths "/*"  
      
artifacts:
  files:
    - '**/*'
  base-directory: 'build'        
      